### PR TITLE
docs: enhance setup instructions

### LINKED ISSUE #53: Better install instructions
Can we get some better installation instructions?

I'm struggling to understand what exactly I need to do in order to use this action.

Step 1 states "Create a repository to host this GitHub Action or select an existing repository."

Do I fork this repo? Clone it then upload to me own account? Or if I select a pre-existing repo, is it the one I want to be scanned? 

Step 2 "Create the env values from the sample workflow below (GH_TOKEN, SEARCH_QUERY) with your information as repository secrets. More info on creating secrets can be found [here](https://docs.github.com/en/actions/security-guides/encrypted-secrets). Note: Your GitHub token will need to have read access to the repository in the organization that you want evaluated"

Where do I put these env vars? I see an .env-example file, so I guess I need an .env file, but where would it go? In the repo I want scanning, or in some other repo (see issues with step 1)

### PR DESCRIPTION
**Pull request by zkoppert**
related to #53

cc/ @paul-uz for review and feedback

### CODE REVIEW

**Comment by paul-uz** [comment]
The instructions for setting up a usable token aren't clear. The linked page just tells you how to create a secret, and doesn't explain how to create a valid token with the correct permissions.

**Comment by zkoppert** [comment]
Going to merge this through as I responded to your feedback. If there is anything else I can clarify here, let me know!

**Review by saze40 — COMMENTED** [review]
cfd

**Review by saze40 — COMMENTED** [review]
cfdxcvv

**Review by saze40 — COMMENTED** [review]
cfdxcvv

**Review by saze40 — COMMENTED** [review]
ghj

**Pull request merged**
