### PR TITLE
docs: Add team assignment

### LINKED ISSUE #52: Assign members of a GitHub team handle in addition of individuals
First of all, thank you very much for open sourcing this action. It has potential to replace one of our internally homegrown workflows.

Here's my request:
Instead of assigning myself to the issue, I'd like the action to support setting a GitHub team handle as `assignee` and assign the members of that team instead.

### PR DESCRIPTION
**Pull request by zkoppert**
fixes #52

### CODE REVIEW

**Comment by julioz** [comment]
Thanks. An important part we're missing here is that the GitHub Action machine account must have the permissions to read the organizations' teams and their members. Without it, jq will take an empty list as input (`gh api` outputs nothing to stdout).

**Comment by zkoppert** [comment]
@julioz I don't see organization team members as an option in the [list of permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) to assign. Do you know how to assign this? Maybe we need a step to use a custom token to auth into the gh api tool. I can ask around here as well.

**Comment by julioz** [comment]
Yep precisely, the token needs to be generated with these permissions and set as a repository secret.

**Comment by zkoppert** [comment]
I see now, maybe we should just change `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` to be `GITHUB_TOKEN: ${{ secrets.CUSTOM_API_TOKEN }}` and give instructions for how to create a token and what permissions. I'll work on that.

**Comment by zkoppert** [comment]
https://github.com/github/issue-metrics/pull/64 to update the documentation. Thanks for the heads up on this! Feel free to review the PR.

**Pull request merged**
